# Generated by Django 4.0.5 on 2022-06-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(blank=True, max_length=200, null=True)),
                ('download_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
