# Generated by Django 4.0.5 on 2022-10-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Panda',
        ),
    ]
