# Generated by Django 4.0.5 on 2022-10-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panda', '0002_delete_panda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.CharField(max_length=256)),
                ('hash_value', models.CharField(max_length=10)),
            ],
        ),
    ]
