# Generated by Django 4.0.5 on 2022-10-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='DownloadLinks',
        ),
    ]
