# Generated by Django 4.0.5 on 2022-10-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panda', '0004_rename_links_downloadlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadlinks',
            name='hash_value',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='downloadlinks',
            name='original_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
